ALTER TABLE auth_users
  ADD COLUMN role ENUM('user', 'admin') NOT NULL DEFAULT 'user' AFTER nickname;

ALTER TABLE books
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD UNIQUE KEY books_isbn_unique (ISBN),
  ADD KEY books_title_index (title),
  ADD KEY books_language_index (language);

ALTER TABLE authors
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD UNIQUE KEY authors_author_name_unique (author_name);

ALTER TABLE publisher
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD UNIQUE KEY publisher_publisher_name_unique (publisher_name);

ALTER TABLE book_img
  MODIFY COLUMN image_url VARCHAR(500) NOT NULL,
  MODIFY COLUMN is_thumbnail TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD KEY book_img_thumbnail_index (book_id, is_thumbnail);
